apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    app: helloworld
spec:
  ports:
  - port: 80
    targetPort: app-port
    protocol: TCP
  selector:
    app: helloworld
  type: LoadBalancer