apiVersion: v1
kind: Service
metadata:
  name: helloworld-db-service
  labels:
    app: helloworld-db
spec:
  ports:
  - port: 3000
    protocol: TCP
  selector:
    app: helloworld-db
  type: LoadBalancer
